import imagepath_t from "../../app/constant/imagepath_t";

export const AttedanceData = [
  { id: 1, name: "Aarav", image: imagepath_t.studen1 },
  { id: 2, name: "Diya", image: imagepath_t.studen2 },
  { id: 3, name: "Kabir", image: imagepath_t.studen3 },
  { id: 4, name: "Meera", image: imagepath_t.studen4 },
  { id: 5, name: "Vivaan", image: imagepath_t.studen1 },
  { id: 6, name: "Sanya", image: imagepath_t.studen2 },
  { id: 7, name: "Ishaan", image: imagepath_t.studen3 },
  { id: 8, name: "Tara", image: imagepath_t.studen4 },
  { id: 9, name: "Aditya", image: imagepath_t.studen1 },
  { id: 10, name: "Kavya", image: imagepath_t.studen2 },
  { id: 11, name: "Dev", image: imagepath_t.studen3 },
  { id: 12, name: "Simran", image: imagepath_t.studen4 },
  { id: 13, name: "Yash", image: imagepath_t.studen1 },
  { id: 14, name: "Nisha", image: imagepath_t.studen2 },
  { id: 15, name: "Rohan", image: imagepath_t.studen3 },
  { id: 16, name: "Anaya", image: imagepath_t.studen4 },
  { id: 17, name: "Aryan", image: imagepath_t.studen1 },
  { id: 18, name: "Myra", image: imagepath_t.studen2 },
  { id: 19, name: "Reyansh", image: imagepath_t.studen3 },
  { id: 20, name: "Pihu", image: imagepath_t.studen4 },
  { id: 21, name: "Ayaan", image: imagepath_t.studen1 },
  { id: 22, name: "Riya", image: imagepath_t.studen2 },
  { id: 23, name: "Vihaan", image: imagepath_t.studen3 },
  { id: 24, name: "Neha", image: imagepath_t.studen4 },
  { id: 25, name: "Laksh", image: imagepath_t.studen1 },
  { id: 26, name: "Sneha", image: imagepath_t.studen2 },
  { id: 27, name: "Krish", image: imagepath_t.studen3 },
  { id: 28, name: "Tanvi", image: imagepath_t.studen4 },
  { id: 29, name: "Raj", image: imagepath_t.studen1 },
  { id: 30, name: "Ira", image: imagepath_t.studen2 },
];
